default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 123456
  host: localhost
  port: 3000


development:
  <<: *default
  database: tornado_morgan_development

test:
  <<: *default
  database: tornado_morgan_test

production:
  <<: *default
  database: tornado_morgan_production

